### ISSUE TITLE
Add bypass mechanism description

### ISSUE THREAD

**Issue by sempasha** [vova7878-modules/PaySecurityBypass#2]
Could you add bypass mechanism description, or even better module or build tools source code.
Thank you for your work.

**Comment by vova7878** [comment]
Вот 100% запарились с переводом на английский, только зачем?)

Исходный код самого модуля закрыт потому что его открытие ускорило бы появление новых вариантов защиты у MirPay и СБПэй. Но все утилиты, которые он использует, имеют открытый код и лежат в моём профиле (К сожалению у меня всё достаточно плохо с документацией - там внутри только код без каких либо комментариев).

[ZygoteLoader](https://github.com/vova7878/ZygoteLoader) используется для запуска моего java кода из под zygisk.
[AndroidVMTools](https://github.com/vova7878/AndroidVMTools) используется для хуков (по сути выполняет работу lsposed)

Наверно вы правы и стоит добавить это в описание
