### ISSUE TITLE
На андроиде 15 уходит в бутлуп

### ISSUE THREAD

**Issue by vec137** [vova7878-modules/PaySecurityBypass#3]
У меня стоит стоковая прошивка Android 15 AP3A.241005.015.A2. После установки модуля ушёл в бутлуп :(

**Comment by vova7878** [comment]
Вы уверены, что бутлуп вызвал именно мой модуль? Какие действия ещё вы делали до перезагрузки? Загружается ли после удаления модуля?

**Comment by vec137** [comment]
Я видимо сам был виноват, отключил mir pay security в lsposed и сразу после установил ваш модуль. В общем теперь всё в порядке, загружается нормально, модуль тоже работает)
